### ISSUE TITLE
Should compose2nix reconsider relative volumes mounts from cwd?

### ISSUE THREAD

**Issue by bLuka** [aksiksi/compose2nix#17]
Hi!

`compose2nix` really is awesome, and exceeds all of my expectations!

As I’m migrating a bunch of Docker Compose definitions, I was wondering if it would be wise to add an option to the parser to handle relative volume mountpoints more effectively.

It would leverage the issue where a `docker-compose.yml` contains a bunch of relative mountpoints from the current working directory.

### Current behavior

Currently, with the following definition:

```yaml
services:
   foo:
      image: bar
      volumes:
        - ./baz:/baz
```

Using `compose2nix -project fo`, the following Nix definition is generated:

```nix
{
  # …
  # Containers
  virtualisation.oci-containers.containers."foo-foo" = {
    image = "bar";
    volumes = [
      "baz:/baz:rw" # <---
    ];
    # …
  };
  # …
}
```

### Expected

Instead, I’d expect either a warning or the following output:

```nix
    volumes = [
      "/some/cwd/from/compose2nix/baz:/baz:rw"
    ];
```

## Propositions

I considered those 2 options:
1. Re-use the current working directory during `compose2nix` call (fastest but dumbest, and might break things if `docker-compose` wasn’t meant to be called from the same place `compose2nix` have been)
2. Add a flag to prefix the relative volume paths by the given directory (smartest, but requires checking help and yet another mandatory flag)

In any way, by default, I believe we should not let `compose2nix` trim the `./` prefix from relative volume mountpoints. We might want to consider issuing a warning instead (as it is done using `-check_systemd_mounts`)

**Comment by aksiksi** [comment]
Thanks for reporting this issue!

So it's probably the underlying `compose-go` library that's stripping out the `./` prefix. I think I like a mix of options (1) and (2): we can check if the path is absolute, and if it isn't, prepend a configurable directory (defaulting to `cwd`).

Note that even if kept the `./` prefix, `compose2nix` would never be able to correctly use relative bind mounts. The reason is that the `volumes` setting is used by the NixOS `oci-containers` module, which ends up mapping each service into a systemd config. As a result, we cannot rely on knowing where the bind mount would be relative to.

**Comment by bLuka** [comment]
Hey, I wanted to give it a try to fix it, but I had a hard time figuring out which packages I should have updated. Your fix looks great, thank you very much for the update and the hard work! 🙂

**Comment by aksiksi** [comment]
@bLuka Sorry, I mistakenly ended up closing your PR while trying to update your fork's branch :/

I have a branch setup on this repo called `escape-chars` with your original commit + a few changes on top with no merge conflicts. Not sure if you can open a PR using it, but give a shot and we can merge it. Otherwise, you should be able to sync your fork and open a PR using the `escape-chars` branch from your fork.
