### ISSUE TITLE
Cannot connect to more than one network

### ISSUE THREAD

**Issue by oskardotglobal** [aksiksi/compose2nix#24]
In a docker run command you cannot specify multiple networks: https://stackoverflow.com/questions/60301221/docker-container-cannot-be-connected-to-network-endpoints

However, when specifying multiple networks with compose2nix, the `--network` flag is appended twice, which leads to the container not starting.

**Comment by aksiksi** [comment]
Can you share the output of `docker version`?

**Comment by aksiksi** [comment]
Because according to https://github.com/moby/moby/issues/35543, multiple networks are supported as of Docker v25.0.0.

You can override the Docker version using the `package` option: https://search.nixos.org/options?channel=24.05&show=virtualisation.docker.package&from=0&size=50&sort=relevance&type=packages&query=++++virtualisation.docker.package

**Comment by oskardotglobal** [comment]
Yup, this is on Docker v24.0.9. Maybe mention this in the readme somewhere?

**Comment by aksiksi** [comment]
Actually, the Docker fix I referenced above might not be working... I hit the same error when trying to update the integration test to use multiple networks with `docker_25`.

There might be a way to fix this: add a `PostStart` hook that runs `docker network connect ...` for the additional networks. This can be achieved using systemd `PostStart`, but the tricky part is how to keep the container stopped until the container is connected to all networks.
