### ISSUE TITLE
OCI container start script doesn't block

### ISSUE THREAD

**Issue by aksiksi** [aksiksi/compose2nix#3]
I'm sure there is a reason for this, but it means that `depends_on` doesn't actually wait for the container(s) to come up.

Would be good to at least document this difference (along with any others).

**Comment by sirchia** [comment]
I believe this is caused by the behaviour of the sdnotify option i.c.w. systemd. https://docs.podman.io/en/latest/markdown/podman-run.1.html#sdnotify-container-conmon-healthy-ignore
It seems the default behaviour in that context is actually ‘conmon’, causing it to be notifying successful startup and return immediately as the container is starting up. I have configured some of my containers to ‘healthy’ with appropriate health checks and some as ‘container’ when the application itself can monitor sdnotify and respond when the application is ready. This causes the container start jobs to await those conditions. 

As an added bonus, it also plays along nicely with podman auto-update, allowing for auto rollback on a failed update.

**Comment by aksiksi** [comment]
Interesting. I guess the default behavior makes sense then. Also, it appears that Nix is mirroring ([here](https://github.com/NixOS/nixpkgs/blob/nixos-23.11/nixos/modules/virtualisation/oci-containers.nix#L294-L295)) the options set by [`podman-generate-systemd`](https://docs.podman.io/en/latest/markdown/podman-generate-systemd.1.html).

One more option for Podman users is `--requires`: https://docs.podman.io/en/latest/markdown/podman-run.1.html#requires-container

But based on the above, there does not seem to be a solution that applies to everyone (and to both Podman and Docker).
